greads/books/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'

urlpatterns = [
    url(r'^book/$', views.BookListView.as_view(), name='books'),
    url(r'^search/$', views.es_search, name='esearch'),
    url(r'^book/results/$', views.search, name='search'),
    url(r'^book/show/(?P<pk>\d+)/$', views.BookDetailView.as_view(),
        name='book-detail'),
    url(r'^genres/$', views.GenreListView.as_view(), name='genres'),
    url(r'^genres/results/$', views.genresearch, name='gsearch'),
]

urlpatterns += [
    url('book/create/', views.add_book, name='add_book'),
    url('book/<int:pk>/update/', views.BookUpdate.as_view(),
        name='book_update'),
    url('book/<int:pk>/confirm/', views.BookConfirm,
        name='book_delete_confirm'),
    url('book/<int:pk>/delete/', views.BookDelete.as_view(),
        name='book_delete'),
]

urlpatterns += [
    url('author/add/', views.add_author, name='add_author'),
    url(r'^author/show/(?P<pk>\d+)/$', views.AuthorDetailView.as_view(),
        name='author-detail'),
    url('author/<int:pk>/update/', views.AuthorUpdate.as_view(),
        name='author_update'),
    url('author/<int:pk>/confirm/', views.AuthorConfirm,
        name='author_delete_confirm'),
    url('author/<int:pk>/delete/', views.AuthorDelete.as_view(),
        name='author_delete'),
]

urlpatterns += [
    url('genre/add/', views.add_genre, name='add_genre'),
    url(r'^genre/show/(?P<name>[\w\s-]+)/$', views.get_genre,
        name='genre-detail'),
    url('genre/<int:pk>/update/', views.GenreUpdate.as_view(),
        name='genre_update'),
    url('genre/<int:pk>/confirm/', views.GenreConfirm,
        name='genre_delete_confirm'),
    url('genre/<int:pk>/delete/', views.GenreDelete.as_view(),
        name='genre_delete'),
]

greads/greads/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic.base import TemplateView
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),

    # signup
    url(r'^signup/$', accounts_views.signup, name='signup'),

    # Login/logout
    url(r'^login/$', auth_views.LoginView.as_view(
        template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # password reset before account login
    url(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ), name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    # change password after account login
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='password_change_done.html'),
        name='password_change_done'),

    # accounts url
    url(r'^account/', include('accounts.urls')),

    # books url
    url(r'^books/', include('books.urls')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greads/books/models.py
from django.contrib.auth.models import User
from django.core.validators import URLValidator
from django.db import models

from .search import BookIndex


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=2000, null=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    website = models.CharField(validators=[URLValidator()], max_length=200,
                               blank=True)
    twitter_id = models.CharField(max_length=200, blank=True)
    email_id = models.EmailField(max_length=200, null=True, blank=True)
    # member_since = models.DateField()
    about = models.TextField(max_length=3000, null=True)

    class Meta:
        unique_together = (("first_name", "last_name"),)

    def __str__(self):
        return '{0} {1}'.format(self.first_name, self.last_name)


class Book(models.Model):
    isbn = models.CharField(max_length=13, primary_key=True)
    title = models.CharField(max_length=200)
    author = models.ManyToManyField(Author)
    genre = models.ManyToManyField(Genre)
    summary = models.TextField(max_length=3000, blank=True)
    # published_year = models.DateField()
    cover_picture = models.ImageField(upload_to='cover_pic',
                                      blank=True)
    # publisher = models.CharField(max_length=100)
    # no_of_pages = models.IntegerField()

    def __str__(self):
        return self.title

    def indexing(self):
        obj = BookIndex(
            meta={'_id': self.isbn},
            title=self.title
        )
        obj.save()
        return obj.to_dict(include_meta=True)


SHELF_CHOICE = (
    ('none', 'Not added to shelf'),
    ('read', 'Read'),
    ('want to read', 'Want to read'),
    ('currently reading', 'currently reading'),
)


class UserBook(models.Model):
    user_book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    reader = models.ForeignKey(User, on_delete=models.SET_NULL,
                               null=True)
    shelf = models.CharField(max_length=100, choices=SHELF_CHOICE,
                             default='none')
    total_books = models.PositiveIntegerField(default=0)
    modified_on = models.DateField()

    class Meta:
        unique_together = (("user_book", "reader"),)

    def __str__(self):
        return '{0}'.format(self.user_book)

greads/books/forms.py
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset

from .models import Book, Author, Genre, UserBook


class BookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # make summary and cover_picture optional fields
        self.fields['summary'].required = False
        self.fields['cover_picture'].required = False

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'isbn',
                'title',
                'author',
                'genre',
                'summary',
                'cover_picture'
            )
        )

    class Meta:
        model = Book
        fields = "__all__"


class UserBookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'shelf'
            )
        )

    class Meta:
        model = UserBook
        fields = "__all__"


class AuthorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['website'].required = False
        self.fields['twitter_id'].required = False
        self.fields['email_id'].required = False

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'first_name',
                'last_name',
                'website',
                'twitter_id',
                'email_id',
                'about'
            )
        )

    class Meta:
        model = Author
        fields = "__all__"


class GenreForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'name',
                'description'
            )
        )

    class Meta:
        model = Genre
        fields = "__all__"

greads/books/views.py
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView, FormView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Book, Author, Genre, UserBook
from .forms import BookForm, AuthorForm, GenreForm, UserBookForm
from .search import BookIndex
from .tasks import update_book_cover_summary


# Create your views here.
def es_search(request):
    template = 'books/book_list.html'
    tagHtml = False

    if request.method == 'POST':
        search_text = request.POST['search_text']
    else:
        search_text = ''

    if len(search_text) > 0:
        tagHtml = True

    s = BookIndex.search().query("match", title=search_text)
    response = s.execute()
    response_dict = response.to_dict()
    hits = response_dict['hits']['hits']
    titles = [hit['_source']['title'] for hit in hits]
    book_id = [hit['_id'] for hit in hits]

    book_list = zip(titles, book_id)
    length = len(titles)

    return render(request, template, {'book_list': book_list,
                                      'length': length,
                                      'tagHtml': tagHtml})


def search(request):
    template = 'books/search_book_list.html'
    page = request.GET.get('page', 1)

    query = request.GET['q']
    search_list = Book.objects.filter(title__icontains=query)

    paginator = Paginator(search_list, 5)
    try:
        search_list = paginator.page(page)
    except PageNotAnInteger:
        search_list = paginator.page(1)
    except EmptyPage:
        search_list = paginator.page(paginator.num_pages)

    return render(request, template, {'search_list': search_list,
                                      'query': query})


def genresearch(request):
    template = 'books/search_genre.html'

    query = request.GET['q']
    search_list = Book.objects.filter(genre__name__icontains=query).distinct()

    return render(request, template, {'search_list': search_list,
                                      'query': query})


def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form_isbn = form.cleaned_data['isbn']
            book = form.save(commit=False)
            book.save()
            form.save_m2m()
            update_book_cover_summary.delay(form_isbn)
            return redirect('home')
    else:
        form = BookForm()

    return render(request, 'books/bookform.html', {'form': form})


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    template_name_suffix = '_update_form'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books:books')


def BookConfirm(request, pk=Book.isbn):
    name = Book.objects.get(isbn=pk)
    isbn = pk
    context = {
        'name': name,
        'isbn': isbn
    }
    return render(request, 'books/book_confirm_delete.html',
                  context)


class BookListView(generic.ListView):
    model = Book
    template_name = 'books/book_list.html'
    context_object_name = 'book_list'
    paginate_by = 3
    queryset = Book.objects.all()


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    pk_url_kwarg = 'pk'
    template_name = 'books/book_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['userbook'] = UserBook.objects.filter(user_book=self.object)
        context['user'] = self.request.user
        return context


def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save()
            author.save()
            return redirect('books:add_book')
    else:
        form = AuthorForm()

    return render(request, 'books/authorform.html', {'form': form})


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'books/author_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def AuthorConfirm(request, pk=Author.id):
    name = Author.objects.get(book_id=pk)
    book_id = pk
    context = {
        'name': name,
        'id': book_id
    }
    return render(request, 'books/author_confirm_delete.html',
                  context)


class AuthorUpdate(UpdateView):
    model = Book
    fields = '__all__'


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('books:books')


def add_genre(request):
    if request.method == "POST":
        form = GenreForm(request.POST)
        if form.is_valid():
            genre = form.save()
            genre.save()
            return redirect('books:add_book')
    else:
        form = GenreForm()

    return render(request, 'books/genreform.html', {'form': form})


def GenreConfirm(request, pk=Genre.id):
    name = Genre.objects.get(book_id=pk)
    book_id = pk
    context = {
        'name': name,
        'id': book_id
    }
    return render(request, 'books/genre_confirm_delete.html',
                  context)


class GenreUpdate(UpdateView):
    model = Book
    fields = '__all__'


class GenreDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('books:books')


class GenreListView(ListView):
    model = Genre
    context_object_name = 'genres'
    template_name = 'genre_list.html'


def get_genre(request, name):
    genre = get_object_or_404(Genre, name=name)

    return render(request, 'books/genre_detail.html', {'genre': genre})

greads/books/templates/books/author_detail.html
{% extends "base.html" %}

{% block content %}

<h3>{{ author.first_name }}</h3> <h3>{{ author.last_name }}</h3>

<br>
<p>Website : {{ author.website }}</p>
<p>Twitter : {{ author.twitter_id }}</p>
<p>Email   : {{ author.email_id }}</p>

<br>
<h3>About</h3>
<p>{{ author.about }}</p>


{% endblock%}

greads/books/templates/books/authorform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Author{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>add author</title>
</head>
<body>
	<br/>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
    	<button type="submit">Save</button>
	</form>
	<br/>

</body>
</html>
{% endblock %}

greads/books/templates/books/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ name }}?</p>

<form action="{% url 'books:book_delete' pk=isbn %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

greads/books/templates/books/book_detail.html
{% extends "base.html" %}

{% block content %}

{% if 'https' in book.cover_picture|stringformat:"s" %}
    <a href="#"><img src="{{ book.cover_picture }}" width="75"></a>
{% else %}
    <a href="#"><img src="{{ book.cover_picture.url }}" width="75"></a>
{% endif %}

<br>

<h3>{{ book.title }}</h3>
by
{% for author in book.author.all %}
    <a href="{% url 'books:author-detail' pk=author.id %}">{{author}}</span></a><br>
{% endfor %}

<br>
<p>{{ book.summary }}</p>

{% for copy in book.userbook_set.all %}
	{% if copy.reader == user %}
      <hr>
      {% if copy.shelf != 'none' %}
        <p><strong>Book added to shelf:</strong> {{copy.shelf}}</p>
      {% endif %}
      {% endif %}
{% endfor %}

<br>
<form action="{% url 'books:book_delete_confirm' %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>
<p>
{% endblock%}

greads/books/templates/books/book_list.html
{% if tagHtml %}
	{% if length > 0 %}
		{% for title,book_id in book_list %}
        	<li><a href="{% url 'books:book-detail' book_id %}">{{title}}</a></li>
		{% endfor %}
	{% else %}
		No results found
	{% endif %}
{% endif %}

greads/books/templates/books/book_update_form.html
{% extends "base.html" %}

{% block content %}

<h1>Update Book</h1>

<form action="{% url 'books:book_update' pk=book.isbn %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

{% endblock %}

greads/books/templates/books/bookform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Book{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>add</title>
</head>
<body>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
    	<button type="submit">Save</button>
	</form>
	<p></p>
	<a href="{% url 'books:add_author' %}"">Add author</a>
	<a href="{% url 'books:add_genre' %}"">Add genre</a>

</body>
</html>
{% endblock %}

greads/books/templates/books/genre_detail.html
{% extends "base.html" %}

{% block content %}

<h3>{{ genre.name | escape }}</h3>

<br>
{{ genre.description }}

{% endblock%}

greads/books/templates/books/genre_list.html
{% extends 'base.html' %}

{% load static %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Genre</li>
{% endblock %}

{% block content %}

<h2>Search genre</h2>
        <form class="form-inline" method="GET" action="{% url 'books:gsearch' %}">
          <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Find genre</button>
        </form>
      </nav>

      <br>

      <section id=genre-list>
    <div class="u-defaultType">
          
      <div class="column" style="width: 25%">
                  <a class="gr-hyperlink" href="#">Art</a><br>

                  <a class="gr-hyperlink" href="#">Biography</a><br>

                  <a class="gr-hyperlink" href="#">Business</a><br>

                  <a class="gr-hyperlink" href="#">Children's</a><br>

                  <a class="gr-hyperlink" href="#">Christian</a><br>

                  <a class="gr-hyperlink" href="#">Classics</a><br>

                  <a class="gr-hyperlink" href="#">Comics</a><br>

                  <a class="gr-hyperlink" href="#">Cookbooks</a><br>

      </div>
      <div class="column" style="width: 25%">
                  <a class="gr-hyperlink" href="#">Ebooks</a><br>

                  <a class="gr-hyperlink" href="#">Fantasy</a><br>

                  <a class="gr-hyperlink" href="#">Fiction</a><br>

                  <a class="gr-hyperlink" href="#">Graphic Novels</a><br>

                  <a class="gr-hyperlink" href="#">Historical Fiction</a><br>

                  <a class="gr-hyperlink" href="#">History</a><br>

                  <a class="gr-hyperlink" href="#">Horror</a><br>

                  <a class="gr-hyperlink" href="#">Memoir</a><br>

      </div>
      <div class="column" style="width: 25%">
                  <a class="gr-hyperlink" href="#">Music</a><br>

                  <a class="gr-hyperlink" href="#">Mystery</a><br>

                  <a class="gr-hyperlink" href="#">Nonfiction</a><br>

                  <a class="gr-hyperlink" href="#">Poetry</a><br>

                  <a class="gr-hyperlink" href="#">Psychology</a><br>

                  <a class="gr-hyperlink" href="#">Romance</a><br>

                  <a class="gr-hyperlink" href="#">Science</a><br>

                  <a class="gr-hyperlink" href="#">Science Fiction</a><br>

      </div>
      <div class="column" style="width: 25%">
                  <a class="gr-hyperlink" href="#">Self Help</a><br>

                  <a class="gr-hyperlink" href="#">Sports</a><br>

                  <a class="gr-hyperlink" href="#">Thriller</a><br>

                  <a class="gr-hyperlink" href="#">Travel</a><br>

                  <a class="gr-hyperlink" href="#">Young Adult</a><br>

                  <a class="gr-hyperlink" href="#">More genres</a>
                  <br>
                  <br>
                  <br>

      </div>
  </div>
  </section>

<h4>Genres</h4>
<br>
<div class="bigBoxBody">
  	<div class="bigBoxContent containerWithHeaderContent">
          <div class="coverRow">
            <div class="leftAlignedImage bookBox">
				<div class="coverWrapper">
				    <a href="#""><img alt="Book Image" title="" width="115" class="bookImage" src="#"></a>
				</div>
			</div>
			<div class="leftAlignedImage bookBox">
				<div class="coverWrapper">
				    <a href="#""><img alt="Book Image" title="" width="115" class="bookImage" src="#"></a>
				</div>
			</div>
			<div class="leftAlignedImage bookBox">
				<div class="coverWrapper">
				    <a href="#""><img alt="Book Image" title="" width="115" class="bookImage" src="#"></a>
				</div>
			</div>
			<div class="leftAlignedImage bookBox">
				<div class="coverWrapper">
				    <a href="#""><img alt="Book Image" title="" width="115" class="bookImage" src="#"></a>
				</div>
			</div>
			<div class="leftAlignedImage bookBox">
				<div class="coverWrapper">
				    <a href="#""><img alt="Book Image" title="" width="115" class="bookImage" src="#"></a>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

greads/books/templates/books/genreform.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Genre{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title>add genre</title>
</head>
<body>
	<br/>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
    	<button type="submit">Save</button>
	</form>
	<br/>

</body>
</html>
{% endblock %}

greads/books/templates/books/search_book_list.html
{% extends 'base.html' %}


{% block title %}Search List{% endblock %}

{% block content %}
{% if search_list %}
    <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table table-border">
      <tbody>
        {% for book in search_list %}
          <tr>
            <td width="5%" valign="top">
              <div id="320" class="u-anchorTarget">
              {% if 'https' in book.cover_picture|stringformat:"s" %}
                    <a href="#"><img src="{{ book.cover_picture }}" width="75"></a>
                {% else %}
                    <a href="#"><img src="{{ book.cover_picture.url }}" width="75"></a>
                {% endif %}
              </div>
             </td>
             <td width="100%" valign="top">
                <a class="bookTitle" itemprop="url" href="{% url 'books:book-detail' pk=book.isbn %}">
                  <span itemprop="name">{{book.title}}</span>
                </a>
                <br><span class="by">by</span>
                  <span itemprop="author">
                    <div class="authorName__container">
                    {% for author in book.author.all %}
                    <a class="authorName" itemprop="url" href="{% url 'books:author-detail' pk=author.id %}"><span itemprop="name">{{author}}</span></a><br>
                    {% endfor %}
                    </div>
                  </span>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% else %}
    <p>We have no book that contains your search word. Would you like to add one?</p>
    <form action="{% url 'books:add_book' %}" method="get">
      {% csrf_token %}
      <input type="submit" value="Add it!">
    </form>
{% endif %}

{% if search_list.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if search_list.has_previous %}
    <li class="page-item"><a href="?page={{ search_list.previous_page_number }}{% if query %}&q={{query}}{% endif %}">Previous</a></li>
    {% else %}
      <li class="disabled"><span>Previous</span></li>
    {% endif %}
    <li class="page-item"><a class="page-link" href="?page={{ 1 }}{% if query %}&q={{query}}{% endif %}">1</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ 2 }}{% if query %}&q={{query}}{% endif %}">2</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ 3 }}{% if query %}&q={{query}}{% endif %}">3</a></li>
    {% if search_list.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ search_list.next_page_number}}{% if query %}&q={{query}}{% endif %}">Next</a></l>
        {% else %}
      <li class="disabled"><span>Next</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% endblock %}

greads/books/templates/books/search_genre.html
{% extends 'base.html' %}


{% block title %}Search Genre{% endblock %}

{% block content %}
{% if search_list %}
    <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table table-border">
      <tbody>
        {% for book in search_list %}
          <tr>
            <td width="5%" valign="top">
              <div id="320" class="u-anchorTarget"></div>
                <a href="#">image</a>
             </td>
             <td width="100%" valign="top">
                <a class="bookTitle" itemprop="url" href="#">
                  <span itemprop="name">{{book.title}}</span>
                </a>
                <br><span class="by">by</span>
                  <span itemprop="author">
                    <div class="authorName__container">
                    {% for author in book.author.all %}
                    <a class="authorName" itemprop="url" href="#"><span itemprop="name">{{author}}</span></a><br>
                    {% endfor %}
                    </div>
                  </span>

                <br>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% else %}
    <p>We have no book in that genre.</p>
    <form action="{% url 'books:book_add' %}" method="get">
      {% csrf_token %}
      <input type="submit" value="Add it!">
    </form>
{% endif %}
{% endblock %}