greads/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    # User profile
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

]

greads/books/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'

urlpatterns = [
    url(r'^book/$', views.BookListView.as_view(), name='books'),
    url(r'^search/$', views.es_search, name='esearch'),
    url(r'^book/results/$', views.search, name='search'),
    url(r'^book/show/(?P<pk>\d+)/$', views.BookDetailView.as_view(),
        name='book-detail'),
    url(r'^genres/$', views.GenreListView.as_view(), name='genres'),
    url(r'^genres/results/$', views.genresearch, name='gsearch'),
]

urlpatterns += [
    url('book/create/', views.add_book, name='add_book'),
    url('book/<int:pk>/update/', views.BookUpdate.as_view(),
        name='book_update'),
    url('book/<int:pk>/confirm/', views.BookConfirm,
        name='book_delete_confirm'),
    url('book/<int:pk>/delete/', views.BookDelete.as_view(),
        name='book_delete'),
]

urlpatterns += [
    url('author/add/', views.add_author, name='add_author'),
    url(r'^author/show/(?P<pk>\d+)/$', views.AuthorDetailView.as_view(),
        name='author-detail'),
    url('author/<int:pk>/update/', views.AuthorUpdate.as_view(),
        name='author_update'),
    url('author/<int:pk>/confirm/', views.AuthorConfirm,
        name='author_delete_confirm'),
    url('author/<int:pk>/delete/', views.AuthorDelete.as_view(),
        name='author_delete'),
]

urlpatterns += [
    url('genre/add/', views.add_genre, name='add_genre'),
    url(r'^genre/show/(?P<name>[\w\s-]+)/$', views.get_genre,
        name='genre-detail'),
    url('genre/<int:pk>/update/', views.GenreUpdate.as_view(),
        name='genre_update'),
    url('genre/<int:pk>/confirm/', views.GenreConfirm,
        name='genre_delete_confirm'),
    url('genre/<int:pk>/delete/', views.GenreDelete.as_view(),
        name='genre_delete'),
]

greads/greads/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic.base import TemplateView
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),

    # signup
    url(r'^signup/$', accounts_views.signup, name='signup'),

    # Login/logout
    url(r'^login/$', auth_views.LoginView.as_view(
        template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # password reset before account login
    url(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ), name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    # change password after account login
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='password_change_done.html'),
        name='password_change_done'),

    # accounts url
    url(r'^account/', include('accounts.urls')),

    # books url
    url(r'^books/', include('books.urls')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greads/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Home Page{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/homestyle.css' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'image/GRfavicon.png' %}">
    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">GReads</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mainMenu">
        {% if user.is_authenticated %}
          <ul class="navbar-nav">
          <li class="nav-item">
          <a class="nav-link active" href="{% url 'home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">My Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Notifications</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ user.username }}
      </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{% url 'accounts:view_profile'%}">My account</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login'%}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>
  <br>
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    {% endblock body %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

greads/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">GReads</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

greads/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Greads</li>
{% endblock %}

{% block content %}

<div class="leftContainer">
    <div id="browsebox">
      <h3>Search and browse books</h3>
      <div id="searchbox">

      {% csrf_token %}
          <input class="form-control mr-sm-2" id="search" name="search" type="text" placeholder="Search" aria-label="Search">
          <ul id="search-results">
            
          </ul>
          <br>
      </div>
      
      <div class="u-defaultType">
      <div class="columnLeft" style="width: 25%">
              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Art' %}">Art</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Biography' %}">Biography</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Business' %}">Business</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Childrens' %}">Children's</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Christian' %}">Christian</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Classics' %}">Classics</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Comics' %}">Comics</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Cookbooks' %}">Cookbooks</a><br>

      </div>
      <div class="columnLeft" style="width: 25%">
              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Ebooks' %}">Ebooks</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Fantasy' %}">Fantasy</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Fiction' %}">Fiction</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Graphic Novels' %}">Graphic Novels</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Historical Fiction' %}">Historical Fiction</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'History' %}">History</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Horror' %}">Horror</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Memoir' %}">Memoir</a><br>

      </div>
      <div class="columnLeft" style="width: 25%">
              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Music' %}">Music</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Mystery' %}">Mystery</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Nonfiction' %}">Nonfiction</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Poetry' %}">Poetry</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Psychology' %}">Psychology</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Romance' %}">Romance</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Science' %}">Science</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Science Fiction' %}">Science Fiction</a><br>

      </div>
      <div class="columnLeft" style="width: 25%">
              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Self Help' %}">Self Help</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Sports' %}">Sports</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Thriller' %}">Thriller</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Travel' %}">Travel</a><br>

              <a class="gr-hyperlink" href="{% url 'books:genre-detail' 'Young' %}">Young Adult</a><br>

              <a class="gr-hyperlink" href="#">More genres</a>
              <br>
              <br>
              <br>

      </div>
  </div>
  </div>
  </div>
  <br>
  <br>
  <section id="updates">
    <div class="section-content">
      <div class="container">
        <h3>Want to add books to shelves?</h3>
        <p class="lead"></p>
        <div class="row">
          <div class="col-sm-12">
            <div class="card-group">
              <div class="card">
                <div class="card-block">
                  <h5 class="card-title">CURRENTLY READING</h5>
                </div>
                <div class="card-block">
                  <p class="card-text">What are you reading?</p>
                  <form class="form-inline" method="GET" action="{% url 'books:search' %}">
                  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </div>
              <div class="card">
                <div class="card-block">
                  <h5 class="card-title">2019 READING CHALLENGE</h5>
                </div>
                <div class="card-block">
                  <p class="card-text">Set your reading challenge this year</p>
                  <button type="button" class="btn btn-outline-success" data-toggle="Modal" data-target="#MyModal">Save</button>
                </div>
              </div>
              <div class="card">
                <div class="card-block">
                  <h5 class="card-title">WANT TO READ</h5>
                </div>
                <div class="card-block">
                  <p class="card-text">What do you want to read next?</p>
                  <form class="form-inline" method="GET" action="{% url 'books:search' %}">
                  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

greads/templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to GReads{% endblock %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            New to GReads? <a href="{% url 'signup' %}">Sign up</a>
            </div>
        </div>
        <div class="text-center py-2">
          <small>
            <a href="{% url 'password_reset' %}" class="text-muted">Forgot your password?</a>
          </small>
        </div>
      </div>
    </div>
{% endblock %}

greads/templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Change password</button>
      </form>
    </div>
  </div>
{% endblock %}

greads/templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

greads/templates/password_reset.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block title%}Reset your password {% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">GReads</a>
    </h1>
    {% block content %}
    <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
    {% endblock %}
  </div>
{% endblock %}

greads/templates/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

greads/templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

greads/templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

greads/templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your GReads username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The GReads Team

greads/templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}