greads/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    # User profile
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

]

greads/books/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'

urlpatterns = [
    url(r'^book/$', views.BookListView.as_view(), name='books'),
    url(r'^search/$', views.es_search, name='esearch'),
    url(r'^book/results/$', views.search, name='search'),
    url(r'^book/show/(?P<pk>\d+)/$', views.BookDetailView.as_view(),
        name='book-detail'),
    url(r'^genres/$', views.GenreListView.as_view(), name='genres'),
    url(r'^genres/results/$', views.genresearch, name='gsearch'),
]

urlpatterns += [
    url('book/create/', views.add_book, name='add_book'),
    url('book/<int:pk>/update/', views.BookUpdate.as_view(),
        name='book_update'),
    url('book/<int:pk>/confirm/', views.BookConfirm,
        name='book_delete_confirm'),
    url('book/<int:pk>/delete/', views.BookDelete.as_view(),
        name='book_delete'),
]

urlpatterns += [
    url('author/add/', views.add_author, name='add_author'),
    url(r'^author/show/(?P<pk>\d+)/$', views.AuthorDetailView.as_view(),
        name='author-detail'),
    url('author/<int:pk>/update/', views.AuthorUpdate.as_view(),
        name='author_update'),
    url('author/<int:pk>/confirm/', views.AuthorConfirm,
        name='author_delete_confirm'),
    url('author/<int:pk>/delete/', views.AuthorDelete.as_view(),
        name='author_delete'),
]

urlpatterns += [
    url('genre/add/', views.add_genre, name='add_genre'),
    url(r'^genre/show/(?P<name>[\w\s-]+)/$', views.get_genre,
        name='genre-detail'),
    url('genre/<int:pk>/update/', views.GenreUpdate.as_view(),
        name='genre_update'),
    url('genre/<int:pk>/confirm/', views.GenreConfirm,
        name='genre_delete_confirm'),
    url('genre/<int:pk>/delete/', views.GenreDelete.as_view(),
        name='genre_delete'),
]

greads/greads/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic.base import TemplateView
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),

    # signup
    url(r'^signup/$', accounts_views.signup, name='signup'),

    # Login/logout
    url(r'^login/$', auth_views.LoginView.as_view(
        template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    # password reset before account login
    url(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ), name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    # change password after account login
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='password_change_done.html'),
        name='password_change_done'),

    # accounts url
    url(r'^account/', include('accounts.urls')),

    # books url
    url(r'^books/', include('books.urls')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greads/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(upload_to='profile_picture',
                               default='/avatar/profile.png')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

greads/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Profile


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True,
                            widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date', 'avatar')

greads/accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render

from .forms import UserForm, ProfileForm
from .forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()

    return render(request, 'signup.html', {'form': form})


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        update_user_form = UserForm(request.POST, instance=request.user)
        update_profile_form = ProfileForm(request.POST,
                                          instance=request.user.profile)
        if update_user_form.is_valid() and update_profile_form.is_valid():
            user = update_user_form.save()
            profile = update_profile_form.save(commit=False)
            profile.user = user

            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']

            profile.save()

            return redirect('accounts:view_profile')
    else:
        update_user_form = UserForm(instance=request.user)
        update_profile_form = ProfileForm(instance=request.user.profile)

    return render(request, 'accounts/edit_profile.html', {
        'update_user_form': update_user_form,
        'update_profile_form': update_profile_form
    })

greads/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
{% endblock %}

{% block title %}Update User Profile{% endblock %}

{% block content %}
  <div class="container">
    <h2 class="text logo my-4">
      Account settings
    </h1>
  	<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        {{ update_user_form.as_p }}
        {{ update_profile_form.as_p }}
        <br />
        <button type="submit"> Save </button>
    </form>
    <br>
	</div>
{% endblock %}

greads/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
{% endblock %}

{% block title %}User Profile{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text logo my-4">
      Profile
    </h1>
    <div class="card mb-3" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-8">
          <div class="card-body">
        <h5 class="card-title">@{{ user }}</h5>
        <img src="{{ user.profile.avatar.url }}" width="150">
        <p class="card-text">First Name       : {{ user.first_name }} <br>
                             Last Name        : {{ user.last_name }} <br>
                             Email            : {{ user.email}} <br>
                             Location         : {{ user.profile.location }} <br>
                             Date Of Birth    : {{ user.profile.birth_day }} <br>
                             Bio              : {{ user.profile.bio }}</p> <br>

        <form action="{% url 'accounts:edit_profile' %}" method="GET">
        {% csrf_token %}
        <input type="submit" value="Edit">
        </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}